version: '3.8'
services:
  app:
    # Access application from 'http://localhost:8080'
    container_name: alcaval
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: flask run --host '0.0.0.0' --port 8080
    environment:
      - FLASK_APP=run
      - FLASK_ENV=development
      - DB_HOST=mongodb
      - DB_PORT=27017
    env_file: secrets/environs.txt
    ports:
      - 8080:8080
    volumes:
      - ./api:/usr/src/app/api
      - ./application:/usr/src/app/application
      - ./core_lib:/usr/src/app/core_lib
      - ./database:/usr/src/app/database
      - ./docker:/usr/src/app/docker
      - ./openshift:/usr/src/app/openshift
      - ./react_frontend/build:/usr/src/app/react_frontend/build
    user: root
    depends_on:
      - database
      - dbmonitor
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./react_frontend/public:/home/node/app/public
      - ./react_frontend/src:/home/node/app/src
    depends_on:
      - app
  database:
    container_name: mongodb
    image: mongo:latest
    env_file: secrets/environs.txt
    ports:
      - 27017
    volumes:
      - mongodb_volume:/data/db
  dbmonitor:
    # Access Mongo-Express from 'http://localhost:8081'
    container_name: mongo-express
    image: mongo-express
    env_file: secrets/environs.txt
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
     - "8081:8081"
    depends_on:
      - database

volumes:
  mongodb_volume:
